[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "S"]
ignore = ["E203"]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["S101"]
