catalog: main
schema: bluebrick_prod
table: example_sales
adls_account: "<adls-account-name>"
adls_container: "coal"
raw_path: "abfss://coal@<adls-account-name>.dfs.core.windows.net/sales/"
silver_path: "abfss://silver@<adls-account-name>.dfs.core.windows.net/sales_silver/"
