catalogs:
  coal: coal_test
  bronze: bronze_test
  silver: silver_test
  gold: gold_test
  metadata: metadata_test
  logs: logs_test
  config: config_test

# Default catalog to use for sample tables (keep for backward-compatibility)
schema: bluebrick
table: example_sales
adls_account: "<adls-account-name>"
coal_path: "abfss://coal@<adls-account-name>.dfs.core.windows.net/sales/"
bronze_path: "abfss://bronze@<adls-account-name>.dfs.core.windows.net/sales_bronze/"
silver_path: "abfss://silver@<adls-account-name>.dfs.core.windows.net/sales_silver/"
gold_path: "abfss://gold@<adls-account-name>.dfs.core.windows.net/sales_gold/"
metadata_path: "abfss://metadata@<adls-account-name>.dfs.core.windows.net/metadata/"
logs_path: "abfss://logs@<adls-account-name>.dfs.core.windows.net/logs/"
config_path: "abfss://config@<adls-account-name>.dfs.core.windows.net/config/"
