---
name: CI

'on':
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ruff lint
        run: |
          pip install ruff==0.6.3
          ruff check src tests

      - name: Black check
        run: |
          pip install 'black[jupyter]==24.8.0'
          black --check --line-length 100 .

      - name: Pytest
        run: pytest -q
