---
name: Deploy Databricks (dev)

'on':
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'databricks.yml'
      - '.github/workflows/deploy-databricks-dev.yml'
  workflow_dispatch: {}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@v2

      - name: Configure Databricks auth
        shell: bash
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          if [[ -z "$DATABRICKS_HOST" || -z "$DATABRICKS_TOKEN" ]]; then
            echo "DATABRICKS_HOST and DATABRICKS_TOKEN secrets are required" >&2
            exit 1
          fi
          databricks auth profiles-location set ./
          printf "%s\n%s\n" "$DATABRICKS_HOST" "$DATABRICKS_TOKEN" | databricks configure --token

      - name: Deploy bundle (dev)
        run: |
          databricks bundle validate -t dev
          databricks bundle deploy -t dev

      - name: Run quickstart job (dev)
        run: |
          databricks bundle run bluebrick-quickstart -t dev
